name: smap-kriging-r

channels:
  - conda-forge
  - bioconda

dependencies:
  - r-base
  - r-here
  - r-ggplot2
  - r-leaflet
  - r-htmlwidgets
  - r-sf
  - r-dplyr
  - r-shiny
  - r-shinythemes
  - r-htmltools
  - r-viridislite
  - bioconductor-rhdf5
  - pandoc
